"""
This file contains the code for the dynamic selector.
"""

import joblib
import pandas as pd
from pathlib import Path
import os
import numpy as np
import warnings
import sys
from asf.predictors import RandomForestRegressorWrapper
from sklearn.preprocessing import MinMaxScaler

def normalise_selection_model_data(selection_model_data) -> dict:
    """
    Normalises the ELA features in the selection model data using min-max normalisation between 0 and 1 across all functions 
    for the ELA features, and between 1e-12 and 1 across all algorithms for each function.

    Parameters
    ----------
    selection_model_data: dict
        A dictionary where the keys are the switching budgets and the values are the corresponding selection model data as pandas DataFrames.

    Returns
    -------
    normalised_selection_model_data: dict
        A dictionary with the same structure as selection_model_data, but with the ELA features normalised.
    """

    algo_cols = ["Non-elitist", "Elitist", "PSO", "DE", "BFGS", "MLSL"]
    ela_feature_cols = [col for col in selection_model_data.columns if col not in algo_cols + ['fid', 'iid', 'rep','high_level_category']]
    
    normalised_selection_model_data = selection_model_data.copy()

    # Normalise algo cols
    for _, group in normalised_selection_model_data.groupby("fid"):
        idx = group.index
        algo_matrix = normalised_selection_model_data.loc[idx, algo_cols].to_numpy()
        flat_vals = algo_matrix.flatten().reshape(-1, 1)

        scaler = MinMaxScaler(feature_range=(1e-12, 1))
        flat_scaled = scaler.fit_transform(flat_vals).flatten()
        normalised_selection_model_data.loc[idx, algo_cols] = flat_scaled.reshape(algo_matrix.shape)

    # Normalise ELA feature cols

    normalised_selection_model_data[ela_feature_cols] = MinMaxScaler().fit_transform(normalised_selection_model_data[ela_feature_cols])

    return normalised_selection_model_data

def create_selection_model_data(data_path: str, switching_budgets: list, normalise: bool = True, a2_algos: list = ["Elitist", "PSO", "DE", "BFGS", "MLSL"], store_data: bool = False, output_path: str = None):
    """
    Creates the data for training the selection model. It reads the ELA features and achieved regrets from data_collection.py,
    and matches the ELA features with the corresponding regrets according to the switching budget. We use the ELA features of 
    Non-elitist, as this is the A1 algorithms.

    Parameters
    ----------
    data_path: str
        Path to the parent folder containing the data collected in data_collection.py
        The folder structure must be the same as the one created by data_collection.py,
    normalise: bool, optional
        Whether to normalise the ELA features. Default is True.
    a2_algos: list, optional
        List of A2 algorithms to consider. Default is ["Elitist", "PSO", "DE", "BFGS", "MLSL"].
    store_data: bool, optional
        Whether to store the created selection model data as csv files. Default is False.
    output_path: str, optional
        Path to the folder where the created selection model data should be stored if store_data is True

    Returns
    -------
    selection_model_data: List[pd.DataFrame]
        A list of dataframes, one for each switching budget. Each dataframe contains the ELA features and the achieved regrets 
        for the corresponding switching budget, which are used to fit the selection model for that switching budget.
    """
    selection_model_data = {}

    # We load the ELA features based on which we switch. These are the features generated by the A1 algorithm, namely Non-elitist CMA-ES
    ela_features = pd.read_csv(os.path.join(data_path, "ela_features/Non-elitist_B1000_5D/ELA_features.csv"))
    non_elitist_regrets = pd.read_csv(os.path.join(data_path, "achieved_regrets/achieved_regrets_Non-elitist_B1000_5D.csv"))
    for budget in switching_budgets:
        regret_dfs = []
        if budget == 50: continue
        if budget == 1000: continue

        regrets = pd.concat(
            [
                *(pd.read_csv(os.path.join(
                    data_path,
                    f"achieved_regrets/achieved_regrets_{algo}_B{budget}_5D.csv"
                )) for algo in a2_algos),
                non_elitist_regrets,
            ],
            ignore_index=True,
        )
    
        regrets_wide = (
            regrets
            .pivot(
                index=["fid", "iid", "rep"],
                columns="algname",
                values="achieved_regret",
            )
            .rename_axis(columns=None)
            .reset_index()
        )


        ela_features_subset = ela_features[ela_features["ela_budget"] == budget].copy()

        # remove non-feature columns you do not want in final data
        drop_cols = ["a1_budget", "ela_budget", "a2_algorithm"]
        ela_features_subset = ela_features_subset.drop(
            columns=[c for c in drop_cols if c in ela_features_subset.columns]
        )

        print(ela_features_subset)

        selection_model_data_budget = ela_features_subset.merge(
            regrets_wide,
            on=["fid", "iid", "rep"],
            how="inner"
        )

        selection_model_data[budget] = selection_model_data_budget

        if normalise:
            selection_model_data[budget] = normalise_selection_model_data(selection_model_data_budget)

        if store_data:
            if output_path is None:
                raise ValueError("output_path must be provided if store_data is True.")
            os.makedirs(output_path, exist_ok=True)
            budget_output_path = os.path.join(output_path, f"selection_model_data_budget_{budget}_normalised.csv") if normalise else os.path.join(output_path, f"selection_model_data_budget_{budget}.csv")
            selection_model_data[budget].to_csv(budget_output_path, index=False)

    return selection_model_data


class DynamicSelector:
    def __init__(self, switching_budgets: list = [50*i for i in range(1, 21)], data_path: str = None, model_path: str = None):
        """
        Initializes the DynamicSelector.

        Parameters
        ----------
        switching_budgets: list, optional
            A list of switching budgets to consider. Default is [50, 100, ..., 1000].
        data_path: str, optional
            Path to the parent folder containing the data collected in data_collection.py
            The folder structure must be the same as the one created by data_collection.py,
        model_path: str, optional
            Path to the parent folder containing the trained models.
            The folder structure must be the same as the one created by fit_models
        """
        self.switching_budgets = switching_budgets
        if data_path is None and model_path is None:
            raise ValueError("Either data_path or model_path must be provided.")
        if model_path:
            self.models = self.load_models_from_folder(model_path)
            self.data_path = None
        else:
            self.models = None
            self.data_path = data_path
    

    def create_ml_ready_data(self, data_path: str):
        # Implementation for creating ML-ready data
        pass

    def fit_models(self, data_path: str, model_save_path: str = None):
        # Implementation for fitting the selection models for each switching budget
        pass

    def predict(self, features: pd.DataFrame) -> np.ndarray:
        # Implementation for predicting the best A2 algorithm given the ELA features and the switching budget
        pass

if __name__ == "__main__":    # Example usage
    selection_model_data = create_selection_model_data(data_path="./data", switching_budgets=[50*i for i in range(1, 21)], normalise=True, store_data=True, output_path="./data/selection_model_data")