"""
This file contains the code for the dynamic selector.
"""

import joblib
import pandas as pd
from pathlib import Path
import os
import numpy as np
import warnings
import sys

from asf.predictors import RandomForestRegressorWrapper
from asf.selectors import PerformanceModel
from ConfigSpace import ConfigurationSpace

from sklearn.preprocessing import MinMaxScaler

def make_default_performance_model():
    """
    Creates a default performance model using the default configuration of the PerformanceModel class as specified in ASF.

    Returns
    -------
    performance_model: PerformanceModel
        The created PerformanceModel.
    """
    cs = ConfigurationSpace()
    cs_transform = {}

    cs, cs_transform = PerformanceModel.get_configuration_space(
        cs=cs,
        cs_transform=cs_transform,
        parent_param=None,
        parent_value=str(PerformanceModel.__name__),
    )

    default_config = cs.get_default_configuration()

    return PerformanceModel.get_from_configuration(
        default_config,
        cs_transform=None,
        random_state=42,
    )


def normalise_selection_model_data(selection_model_data) -> dict:
    """
    Normalises the ELA features in the selection model data using min-max normalisation between 0 and 1 across all functions 
    for the ELA features, and between 1e-12 and 1 across all algorithms for each function.

    Parameters
    ----------
    selection_model_data: dict
        A dictionary where the keys are the switching budgets and the values are the corresponding selection model data as pandas DataFrames.

    Returns
    -------
    normalised_selection_model_data: dict
        A dictionary with the same structure as selection_model_data, but with the ELA features normalised.
    """

    algo_cols = ["Non-elitist", "Elitist", "PSO", "DE", "BFGS", "MLSL"]
    ela_feature_cols = [col for col in selection_model_data.columns if col not in algo_cols + ['fid', 'iid', 'rep','high_level_category']]
    
    normalised_selection_model_data = selection_model_data.copy()

    # Normalise algo cols
    for _, group in normalised_selection_model_data.groupby("fid"):
        idx = group.index
        algo_matrix = normalised_selection_model_data.loc[idx, algo_cols].to_numpy()
        flat_vals = algo_matrix.flatten().reshape(-1, 1)

        scaler = MinMaxScaler(feature_range=(1e-12, 1))
        flat_scaled = scaler.fit_transform(flat_vals).flatten()
        normalised_selection_model_data.loc[idx, algo_cols] = flat_scaled.reshape(algo_matrix.shape)

    # Normalise ELA feature cols

    normalised_selection_model_data[ela_feature_cols] = MinMaxScaler().fit_transform(normalised_selection_model_data[ela_feature_cols])

    return normalised_selection_model_data

def create_selection_model_data(data_path: str, switching_budgets: list, normalise: bool = True, a2_algos: list = ["Elitist", "PSO", "DE", "BFGS", "MLSL"], store_data: bool = False, output_path: str = None):
    """
    Creates the data for training the selection model. It reads the ELA features and achieved regrets from data_collection.py,
    and matches the ELA features with the corresponding regrets according to the switching budget. We use the ELA features of 
    Non-elitist, as this is the A1 algorithms.

    Parameters
    ----------
    data_path: str
        Path to the parent folder containing the data collected in data_collection.py
        The folder structure must be the same as the one created by data_collection.py,
    normalise: bool, optional
        Whether to normalise the ELA features. Default is True.
    a2_algos: list, optional
        List of A2 algorithms to consider. Default is ["Elitist", "PSO", "DE", "BFGS", "MLSL"].
    store_data: bool, optional
        Whether to store the created selection model data as csv files. Default is False.
    output_path: str, optional
        Path to the folder where the created selection model data should be stored if store_data is True

    Returns
    -------
    selection_model_data: dict
        A dictionary where the keys are the switching budgets and the values are the corresponding selection model data as pandas DataFrames.
    """
    selection_model_data = {}

    # We load the ELA features based on which we switch. These are the features generated by the A1 algorithm, namely Non-elitist CMA-ES
    ela_features = pd.read_csv(os.path.join(data_path, "ela_features/Non-elitist_B1000_5D/ELA_features.csv"))
    non_elitist_regrets = pd.read_csv(os.path.join(data_path, "achieved_regrets/achieved_regrets_Non-elitist_B1000_5D.csv"))
    for budget in switching_budgets:
        # regret_dfs = []
        if budget == 50: continue
        if budget == 1000: continue

        regrets = pd.concat(
            [
                *(pd.read_csv(os.path.join(
                    data_path,
                    f"achieved_regrets/achieved_regrets_{algo}_B{budget}_5D.csv"
                )) for algo in a2_algos),
                non_elitist_regrets,
            ],
            ignore_index=True,
        )
    
        regrets_wide = (
            regrets
            .pivot(
                index=["fid", "iid", "rep"],
                columns="algname",
                values="achieved_regret",
            )
            .rename_axis(columns=None)
            .reset_index()
        )


        ela_features_subset = ela_features[ela_features["ela_budget"] == budget].copy()

        # remove non-feature columns you do not want in final data
        drop_cols = ["a1_budget", "ela_budget", "a2_algorithm"]
        ela_features_subset = ela_features_subset.drop(
            columns=[c for c in drop_cols if c in ela_features_subset.columns]
        )

        print(ela_features_subset)

        selection_model_data_budget = ela_features_subset.merge(
            regrets_wide,
            on=["fid", "iid", "rep"],
            how="inner"
        )

        selection_model_data[budget] = selection_model_data_budget

        if normalise:
            selection_model_data[budget] = normalise_selection_model_data(selection_model_data_budget)

        if store_data:
            if output_path is None:
                raise ValueError("output_path must be provided if store_data is True.")
            os.makedirs(output_path, exist_ok=True)
            budget_output_path = os.path.join(output_path, f"selection_model_data_budget_{budget}_normalised.csv") if normalise else os.path.join(output_path, f"selection_model_data_budget_{budget}.csv")
            selection_model_data[budget].to_csv(budget_output_path, index=False)

    return selection_model_data

def get_crossvalidated_predictions(selection_model_training_data: dict, safe: bool = False, data_path: str = "./data", 
                                   no_switch_regrets_path: str = "./data/achieved_regrets/achieved_regrets_Non-elitist_B1000_5D.csv") -> pd.DataFrame:
    """
    Performs leave-one-instance-out cross-validation for each switching budget, and returns a DataFrame containing the predictions and actual regrets for each (fid, iid, rep) and switching budget.
    
    Parameters
    ----------
    selection_model_training_data : dict
        A dictionary containing the training data for each switching budget.
    safe : bool, optional
        Whether to safe the predictions as a csv file, by default False.
    data_path : str, optional
        The path to the data directory in which to store the predictions, by default "./data".
    no_switch_regrets_path : str, optional
        The path to the no-switch regrets CSV file, by default "./data/achieved_regrets/achieved_regrets_Non-elitist_B1000_5D.csv".

    Returns
    -------
    pd.DataFrame
        A DataFrame containing the predictions and actual regrets for each (fid, iid, rep) and switching budget.
    """
    no_switch_regrets = pd.read_csv(no_switch_regrets_path)

    # Only keep rows where iid is in the training set (1,2,3,4,5)
    no_switch_regrets = no_switch_regrets[no_switch_regrets["iid"].isin([1, 2, 3, 4, 5])]

    switching_budgets = sorted(selection_model_training_data.keys())

    algo_cols = ["Non-elitist", "Elitist", "PSO", "DE", "BFGS", "MLSL"]

    prediction_rows = []

    instances = sorted(
        selection_model_training_data[switching_budgets[0]]["iid"].unique()
    )

    for budget in switching_budgets:
        print(f"Processing budget {budget}...")
        data_budget = selection_model_training_data[budget].copy()

        feature_cols = [
            col for col in data_budget.columns
            if col not in ["fid", "iid", "rep"] + algo_cols
        ]

        for instance in instances:
            print(f"Processing instance {instance}...")
            cv_training_data = data_budget[data_budget["iid"] != instance]
            cv_test_data = data_budget[data_budget["iid"] == instance]

            train_keys = list(
                cv_training_data[["fid", "iid", "rep"]]
                .itertuples(index=False, name=None)
            )

            test_keys = list(
                cv_test_data[["fid", "iid", "rep"]]
                .itertuples(index=False, name=None)
            )

            X_train = cv_training_data[feature_cols].copy()
            y_train = cv_training_data[algo_cols].copy()
            X_test = cv_test_data[feature_cols].copy()

            X_train.index = train_keys
            y_train.index = train_keys
            X_test.index = test_keys

            selector = make_default_performance_model()
            selector.algorithms = algo_cols
            selector.fit(X_train, y_train)

            predictions = selector.predict(X_test)


            for (fid, iid, rep), [(algo, _)] in predictions.items():
                actual_value = cv_test_data.loc[
                    (cv_test_data["fid"] == fid)
                    & (cv_test_data["iid"] == iid)
                    & (cv_test_data["rep"] == rep),
                    algo
                ].values[0]

                prediction_rows.append({
                    "fid": fid,
                    "iid": iid,
                    "rep": rep,
                    "budget": budget,
                    "selected_algorithm": algo,
                    "actual_regret": actual_value,
                })

    # Add the no-switch regrets for each instance as well
    for _, row in no_switch_regrets.iterrows():
        prediction_rows.append({
            "fid": row["fid"],
            "iid": row["iid"],
            "rep": row["rep"],
            "budget": 1000,  # We can use budget 1000 to indicate no-switch, as 1000 is the maximum budget
            "selected_algorithm": "Non-elitist",
            "actual_regret": row["achieved_regret"],
        })

    res = pd.DataFrame(prediction_rows)

    res = res.sort_values(by=["fid", "iid", "rep", "budget"]).reset_index(drop=True)

    if safe:
        output_path = os.path.join(data_path, "crossvalidated_predictions.csv")

        if not os.path.exists(data_path):
            os.makedirs(data_path, exist_ok=True)

        res.to_csv(output_path, index=False)
        print(f"Cross-validated predictions saved to {output_path}")

    return res

def find_optimal_budgets_per_run(crossvalidated_predictions: pd.DataFrame, tie_breaking_strategy: str = "highest_budget", safe: bool = False, data_path: str = "./data") -> dict:
    """
    For each (fid, iid, rep), we find the budget where actual_regret is the lowest across all budgets for that (fid,iid,rep).
    If there are ties, we select the budget according to the specified tie-breaking strategy.

    Parameters
    ----------
    crossvalidated_predictions: pd.DataFrame
        A DataFrame containing the predictions and actual regrets for each (fid, iid, rep) and switching budget, as returned by get_crossvalidated_predictions.
    tie_breaking_strategy: str, optional
        The strategy to use for breaking ties when multiple budgets have the same lowest actual_regret. 
        Must be one of "highest_budget" or "lowest_budget". Default is "highest_budget".
    safe: bool, optional
        Whether to save the optimal budgets per run as a csv file, by default False.
    data_path: str, optional
        The path to the data directory in which to store the optimal budgets per run, by default "./data".
    """

    optimal_budgets = {}

    for (fid, iid, rep), group in crossvalidated_predictions.groupby(["fid", "iid", "rep"]):
        min_regret = group["actual_regret"].min()
        best_budgets = group[group["actual_regret"] == min_regret]["budget"].tolist()

        if tie_breaking_strategy == "highest_budget":
            selected_budget = max(best_budgets)
        elif tie_breaking_strategy == "lowest_budget":
            selected_budget = min(best_budgets)
        else:
            raise ValueError(f"Invalid tie-breaking strategy: {tie_breaking_strategy}")

        optimal_budgets[(fid, iid, rep)] = selected_budget

    if safe:
        output_path = os.path.join(data_path, "optimal_budgets.csv")
        pd.DataFrame([
            {"fid": fid, "iid": iid, "rep": rep, "optimal_budget": budget}
            for (fid, iid, rep), budget in optimal_budgets.items()
        ]).to_csv(output_path, index=False)
        print(f"Optimal budgets saved to {output_path}")

    return optimal_budgets


def create_switch_model_data(selection_model_training_data: dict[int, pd.DataFrame], safe: bool = True, data_path: str = "./data", 
                             safe_crossvalidated_predictions: bool = False, safe_optimal_budgets: bool = False) -> pd.DataFrame:
    """
    Creates switching-model training data using leave-one-instance-out CV.
 
    Parameters
    ----------
    selection_model_training_data: dict[int, pd.DataFrame]
        A dictionary where the keys are the switching budgets and the values are the corresponding selection model training data as pandas DataFrames.
    safe: bool, optional
        Whether to save the created switching model training data as csv files. Default is True.
    data_path: str, optional
        Path to the folder where the created switching model training data should be stored if safe is True. Default is "./data".
    safe_crossvalidated_predictions: bool, optional
        Whether to save the cross-validated predictions as csv files. Default is False.
    safe_optimal_budgets: bool, optional
        Whether to save the optimal budgets per run as csv files. Default is False.
    
    Returns
    -------
    switching_model_training_data: dict[int, pd.DataFrame]
        A dictionary where the keys are the switching budgets and the values are the corresponding switching model training
    """
    switching_model_training_data = {}

    switching_budgets = sorted(selection_model_training_data.keys())
    
    crossvalidated_predictions = get_crossvalidated_predictions(selection_model_training_data, safe=safe_crossvalidated_predictions, data_path=data_path)

    optimal_budgets_per_run = find_optimal_budgets_per_run(crossvalidated_predictions, safe=safe_optimal_budgets, data_path=data_path)

    for switching_budget in switching_budgets:
        switching_model_training_data[switching_budget] = selection_model_training_data[switching_budget].copy()

        # Remove algo columns
        
        algo_cols = ["Non-elitist", "Elitist", "PSO", "DE", "BFGS", "MLSL"]
        switching_model_training_data[switching_budget] = switching_model_training_data[switching_budget].drop(columns=algo_cols)

        # Add optimal budget column. Entry is true iff the optimal budget for that (fid, iid, rep) less or equal the current switching_budget
        switching_model_training_data[switching_budget]["optimal_budget"] = switching_model_training_data[switching_budget].apply(
            lambda row: optimal_budgets_per_run[(row["fid"], row["iid"], row["rep"])] <= switching_budget,
            axis=1
        )

    if safe:   
        output_path = os.path.join(data_path, "switching_model_training_data")
        os.makedirs(output_path, exist_ok=True)

        for budget, df in switching_model_training_data.items():
            budget_output_path = os.path.join(output_path, f"switching_model_training_data_budget_{budget}.csv")
            df.to_csv(budget_output_path, index=False)
            print(f"Switching model training data for budget {budget} saved to {budget_output_path}")

    return switching_model_training_data

class DynamicSelector:
    def __init__(self, switching_budgets: list = [50*i for i in range(1, 21)], data_path: str = None, model_path: str = None):
        """
        Initializes the DynamicSelector.

        Parameters
        ----------
        switching_budgets: list, optional
            A list of switching budgets to consider. Default is [50, 100, ..., 1000].
        data_path: str, optional
            Path to the parent folder containing the data collected in data_collection.py
            The folder structure must be the same as the one created by data_collection.py,
        model_path: str, optional
            Path to the parent folder containing the trained models.
            The folder structure must be the same as the one created by fit_models
        """
        self.switching_budgets = switching_budgets
        if data_path is None and model_path is None:
            raise ValueError("Either data_path or model_path must be provided.")
        if model_path:
            self.models = self.load_models_from_folder(model_path)
            self.data_path = None
        else:
            self.models = None
            self.data_path = data_path
    

    def create_ml_ready_data(self, data_path: str):
        # Implementation for creating ML-ready data
        pass

    def fit_models(self, data_path: str, model_save_path: str = None):
        # Implementation for fitting the selection models for each switching budget
        pass

    def predict(self, features: pd.DataFrame) -> np.ndarray:
        # Implementation for predicting the best A2 algorithm given the ELA features and the switching budget
        pass

if __name__ == "__main__":    # Example usage
    selection_model_data = create_selection_model_data(data_path="./data", switching_budgets=[50*i for i in range(2, 21)], normalise=True, store_data=False, output_path="./data/selection_model_data")

    selection_model_training_data = {}
    for budget in selection_model_data:
        selection_model_training_data[budget] = selection_model_data[budget].copy()
        # Remove all rows where iid is not in the training set (1,2,3,4,5)
        selection_model_training_data[budget] = selection_model_training_data[budget][selection_model_training_data[budget]["iid"].isin([1, 2, 3, 4, 5])]

    switching_model_data = create_switch_model_data(selection_model_training_data, safe_crossvalidated_predictions=True, safe_optimal_budgets=True, data_path="./data")